---
AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Base on AWS - Creates Security Groups

Metadata:

  Authors:
    Description: Jorge Rojas (jorgealejandrorojas919@gmail.com)

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: AWS Parameters
      Parameters:
        - SshAccessCidr
        - AlbIngressMode
        - CloudFrontOriginPrefixListId
        - CloudFrontVpcOriginSecurityGroupId
        - Vpc
    ParameterLabels:
      SshAccessCidr:
        default: SSH Access From
      AlbIngressMode:
        default: ALB Ingress Mode
      CloudFrontOriginPrefixListId:
        default: CloudFront Origin Prefix List ID
      CloudFrontVpcOriginSecurityGroupId:
        default: CloudFront VPC Origin Security Group ID
      Vpc:
        default: Vpc Id

Parameters:
  
  SshAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Use a trusted office/VPN CIDR.
    Type: String
    Default: 10.0.0.0/16
  Vpc:
    AllowedPattern: ^(vpc-)([a-z0-9]{8}|[a-z0-9]{17})$
    Description: The Vpc Id of an existing Vpc.
    Type: AWS::EC2::VPC::Id
  AlbIngressMode:
    AllowedValues:
    - internet
    - cloudfront-prefix-list
    - vpc-origin-security-group
    Default: internet
    Description: Controls who can reach the ALB security group.
    Type: String
  CloudFrontOriginPrefixListId:
    AllowedPattern: ^$|^(pl-)([a-z0-9]+)$
    Default: ''
    Description: Required when AlbIngressMode is cloudfront-prefix-list.
    Type: String
  CloudFrontVpcOriginSecurityGroupId:
    AllowedPattern: ^$|^(sg-)([a-z0-9]{8}|[a-z0-9]{17})$
    Default: ''
    Description: Required when AlbIngressMode is vpc-origin-security-group.
    Type: String

Conditions:
  AlbIngressFromInternet: !Equals [!Ref AlbIngressMode, internet]
  AlbIngressFromCloudFrontPrefixList: !Equals [!Ref AlbIngressMode, cloudfront-prefix-list]
  AlbIngressFromVpcOriginSecurityGroup: !Equals [!Ref AlbIngressMode, vpc-origin-security-group]
  HasCloudFrontOriginPrefixListId: !Not [!Equals [!Ref CloudFrontOriginPrefixListId, '']]
  HasCloudFrontVpcOriginSecurityGroupId: !Not [!Equals [!Ref CloudFrontVpcOriginSecurityGroupId, '']]
  CreateAlbIngressFromCloudFrontPrefixList: !And
    - !Condition AlbIngressFromCloudFrontPrefixList
    - !Condition HasCloudFrontOriginPrefixListId
  CreateAlbIngressFromVpcOriginSecurityGroup: !And
    - !Condition AlbIngressFromVpcOriginSecurityGroup
    - !Condition HasCloudFrontVpcOriginSecurityGroupId

Resources:

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Bastion instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshAccessCidr
      VpcId:
        !Ref Vpc

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS Postgres
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BackendSecurityGroup
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      VpcId:
        !Ref Vpc

  PublicAlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId:
        !Ref Vpc

  PublicAlbIngressHttpFromInternet:
    Condition: AlbIngressFromInternet
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicAlbSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  PublicAlbIngressHttpsFromInternet:
    Condition: AlbIngressFromInternet
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicAlbSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0

  PublicAlbIngressHttpFromCloudFrontPrefixList:
    Condition: CreateAlbIngressFromCloudFrontPrefixList
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicAlbSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourcePrefixListId: !Ref CloudFrontOriginPrefixListId

  PublicAlbIngressHttpsFromCloudFrontPrefixList:
    Condition: CreateAlbIngressFromCloudFrontPrefixList
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicAlbSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourcePrefixListId: !Ref CloudFrontOriginPrefixListId

  PublicAlbIngressHttpFromVpcOriginSecurityGroup:
    Condition: CreateAlbIngressFromVpcOriginSecurityGroup
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicAlbSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref CloudFrontVpcOriginSecurityGroupId

  PublicAlbIngressHttpsFromVpcOriginSecurityGroup:
    Condition: CreateAlbIngressFromVpcOriginSecurityGroup
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicAlbSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref CloudFrontVpcOriginSecurityGroupId

  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Backend instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref PublicAlbSecurityGroup
      VpcId:
        !Ref Vpc
 
Outputs:
  BastionSecurityGroup:
    Value: !Ref BastionSecurityGroup
  RDSSecurityGroup:
    Value: !Ref RDSSecurityGroup
  PublicAlbSecurityGroup:
    Value: !Ref PublicAlbSecurityGroup
  BackendSecurityGroup:
    Value: !Ref BackendSecurityGroup
  
