---
AWSTemplateFormatVersion: 2010-09-09

Description: Sample task execution role for ECS Fargate

Parameters:
  SystemName:
    Description: Identifier for the current system and environment
    Type: String

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${SystemName}-task-exec-role"
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
              }
            ]
        }
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
      - PolicyName: AccessSecretsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            Resource: "*"

  ManageAWSServicesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${SystemName}-manage-aws-service-role"
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }

Outputs:
  ManageAWSServicesRole:
    Description: A reference to the Managed service role used as task role
    Value: !Ref ManageAWSServicesRole

  TaskExecutionRole:
    Description: A reference to the task execution role
    Value: !Ref TaskExecutionRole
