---
AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Sample Project on AWS - Creates S3 bucket for backend system

Metadata:

  Authors:
    Description: Jorge Rojas (jorgealejandrorojas919@gmail.com)

Parameters:
  paramBucketName:
    Type: String
    Description: Bucket Name
  paramEnvironment:
    AllowedValues:
    - dev
    - stg
    - prod
    Default: dev
    Description: Number of environments. This must match your selections in the list of environments below.
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub '${paramBucketName}-${paramEnvironment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  S3User:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub 'Sample-bucket-access-${paramEnvironment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*
  
  S3UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User

Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the Amazon S3 bucket.
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Domain Name of the Amazon S3 bucket
  AccessKeyID:
    Value: !Ref S3UserAccessKey
  SecretAccessKey:
    Value: !GetAtt S3UserAccessKey.SecretAccessKey
  BucketName:
    Value: !Ref S3Bucket
  User:
    Value: !Ref S3User